apply plugin: 'com.android.application'
android {
    namespace 'com.ceco.v.gravitybox'
    compileSdkVersion 35
    defaultConfig {
        applicationId 'com.ceco.v.gravitybox'
        minSdkVersion 35
        //noinspection OldTargetApi
        targetSdkVersion 35
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.palette:palette:1.0.0'
    api 'com.vanniktech:android-image-cropper:4.6.0'
}
